#######################################################################
# REN-CYBER Example - Pushing Docker containers to ECR              ###
#######################################################################

name: Ren-hydro-runner-creation

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

##### JOBS#####
jobs:
  docker-build-publish:
    runs-on: docker
    env:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECR_REGION: ${{ secrets.ECR_REGION }}
      IMAGE_TAG: action-demo
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Docker Build       
        run: |
          #########################################################
          ### Docker Build command here                         ###
          #########################################################
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
          
#      - name: Docker Push to ECR
#        run: |
#          #########################################################
#          ### Publishes the built Dockerfile image to AWS ECR   ###
#          ##########################################################
        docker push 532594069918.dkr.ecr.us-east-1.amazonaws.com/actions-demo:actions-demo
